name: docker-build-push

on:
  push:
    branches: 
      - master
    paths: 
      - 'Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/scanicula-aek
          path: ./
          dockerfile: Dockerfile
          tags: v1.0