name: docker-pull

on:
  schedule:
    - cron: 1 11 * * *

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: docker pull alexthiery/scanicula-aek:v1.0
